### ISSUE TITLE
Missing " and ) at end of line

### ISSUE THREAD

**Issue by ghost** [Alydus/liro#11]
https://github.com/Alydus/liro/blob/eee689d91e008aef04135002f75da685d7a37f25/liro/gamemode/liro/moduleloader.lua#L121
Missing a " or ) at the end of the line since there're 7x " and it would have to be 8 it also throws a error at server start. Just a very little thing that everyone could fix, just wanted to tell you :)

And keep up the good work, love your gamemode base with modules. ❤️

**Comment by Alydus** [comment]
Fixed in https://github.com/Alydus/liro/commit/2d645d0cdf8e57621dbb21012fc30a28845bf7e9
