### ISSUE TITLE
(FIX) Issues inside moduleloader.lua

### ISSUE THREAD

**Issue by ghost** [Alydus/liro#12]
The First Problem i noticed was on line 24 where Blacklisted files are still being loaded.

> ```lua
> if string.lower(fileToLoad) != string.lower(liro.config.registerFileName) or not table.HasValue(liro.config.globalBlacklistedFiles, fileToLoad) or not table.HasValue(blacklistedFiles, fileToLoad) then
> ```
> the problem is fixed by removing the if statement and instead do this
> ```lua
> local relativePath = folderPath .. "/" .. fileToLoad
> 
> -- If the file attempting to load if the registermodule file name, it will not load it again
> if string.lower(fileToLoad) == string.lower(liro.config.registerFileName) then continue end
> -- If the file isn't per-module blacklisted, load it
> if table.HasValue(blacklistedFiles, fileToLoad) then continue end
> -- If the file isn't globally blacklisted, load it
> if table.HasValue(liro.config.globalBlacklistedFiles, fileToLoad) then continue end
> 
> -- Define load prefixes, use per-module prefixes, or default (defined in config)
> if moduleData.loadPrefixes != nil and moduleData.loadPrefixes then
> ```

The Second Problem is on line 26 where it checks if loadprefixes are in the module table to change them

> ```lua
> if moduleData.loadPrefixes != nil or not moduleData.loadPrefixes then
> ```
> the problem is fixed by changing 'or not' to 'and'
> ```lua
> if moduleData.loadPrefixes != nil and moduleData.loadPrefixes then
> ```

The Third Problem is around line 45 where it loads the shared files, it will not find the file cause the file is included before the server adds it to the client

> ```lua
> include(relativePath)
> if SERVER then
> AddCSLuaFile(relativePath)
> end
> ```
> the problem is fixed by changing the order
> ```lua
> if SERVER then
> AddCSLuaFile(relativePath)
> end
> include(relativePath)
> ```

Not a Problem but something i noticed in console on line 225/236

> All the `\"` should be removed on line 236 so it does not show the quotes " in the console at disabled 
> modules for better look :)

On line 230/231 between the end's added

> ```lua
> print("//")
> ```
> so that the `////////////////////////////` is not directly under the last loaded module

On line 201 the if statement is made wrong cause of the
> ```lua
> and liro.config.showConsoleLoadSequenceRanksOnly
> ```
it will just show the module load text when it's ranks only, cause when it's false it will not trigger for the client
fix:
> ```lua
> if SERVER or (CLIENT and liro.config.showConsoleLoadSequenceClientside) then
>	local allow = true
>	if CLIENT and liro.config.showConsoleLoadSequenceRanksOnly and not table.HasValue(liro.config.showConsoleLoadSequenceClientsideRanks, LocalPlayer():GetUserGroup()) then
>	    allow = false
>	end
> 
>	if SERVER or (CLIENT and allow) then
>		PRINT LOG
> ```

**Comment by Alydus** [comment]
Appreciated; will be included in V2.
